swagger: '2.0'
info:
  title: 'CVE-Land API'
  description: 'API documentation for CVE-Land'
  version: '1.0'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /v2/{cve}/namespaces:
    get:
      summary: Get namespaces for a CVE
      description: Returns the namespaces for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  namespaces:
                    type: object
                    description: The namespaces for the given CVE.

  /v2/{cve}/mitre:
    get:
      summary: Get MITRE data for a CVE
      description: Returns the MITRE data for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: The MITRE data for the given CVE.

  /v2/{cve}/nist:
    get:
      summary: Get NIST data for a CVE
      description: Returns the NIST data for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: The NIST data for the given CVE.

  /v2/{cve}/nist/description:
    get:
      summary: Get NIST description for a CVE
      description: Returns the NIST description for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                    description: The NIST description for the given CVE.

  /v2/{cve}/nist/base-score:
    get:
      summary: Get NIST base score for a CVE
      description: Returns the NIST base score for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  baseScore:
                    type: number
                    description: The NIST base score for the given CVE.

  /v2/{cve}/nist/exploitability-score:
    get:
      summary: Get NIST exploitability score for a CVE
      description: Returns the NIST exploitability score for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  exploitabilityScore:
                    type: number
                    description: The NIST exploitability score for the given CVE.

  /v2/{cve}/nist/references:
    get:
      summary: Get NIST references for a CVE
      description: Returns the NIST references for a given CVE.
      parameters:
        - name: cve
          in: path
          description: The CVE identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  references:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          description: The URL of the reference.
                        name:
                          type: string
                          description: The name of the reference.